In [2]:
import numpy as np

Basics like initializing the normal array


In [4]:
a=np.array([1,2,3])
a

array([1, 2, 3])

2d arrays


In [6]:
b=np.array([[1,2,3,4],[5,6,7,8]])
print(b)

[[1 2 3 4]
 [5 6 7 8]]


if we simply gives b it gives output as array([1 2 3 4]) if we give print(b) the it gives [1 2 3 4]


In [9]:
#get the dimensions
print(a.ndim) # a.number dimension
print(b.ndim)# b.number dimensions


1
2


In [15]:
#getting shape
#in one dimension no.of elements is givem
#in two dimension rows,columns is given
# in three it gives depth,rows,columns
print(a.shape)
print(b.shape)

(3,)
(2, 4)


In [17]:
#how much space like what datatype
a.dtype

dtype('int64')

In [19]:
#if we want to specify size
a=np.array([1,2,3],dtype='int16')
a.dtype

dtype('int16')

In [22]:
#a.itemsize gives in the form of bytes 1 byte =8bits
#so16 bits =2 bytes it should give 2
a.itemsize

2

In [23]:
b.itemsize

8

In [24]:
a=np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [25]:
a.shape


(2, 7)

In [28]:
#get a specific element....array[row][column]
a[1][3]

11

In [30]:
#we can use negative indexing also
a[1][-4]


11

In [32]:
#get a specific row
print(a[0,:])# gives first row that is row number 0 and all columns needed so : is used

[1 2 3 4 5 6 7]


In [35]:
# get specific columns
print(a[:,3])# gives 3rd column in both

[ 4 11]


In [39]:
#[startindex:lastindex:stepsize]
# 0th row starting from first column to last column print alternately that isstep size is2
print(a[0,1:-1:2])

[2 4 6]


In [40]:
#changing the value
a[1][5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [42]:
a[1,5]=25

In [43]:
a

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 25, 14]])

In [44]:
#entire rows and columns  changed to 50
a[:,:]=50
print(a)

[[50 50 50 50 50 50 50]
 [50 50 50 50 50 50 50]]


In [50]:
a[:,1]=[20,40]
print(a)

[[50 20 20 50 50 50 50]
 [50 40 40 50 50 50 50]]


In [45]:
a[:,2]=20
print(a)

[[50 50 20 50 50 50 50]
 [50 50 20 50 50 50 50]]


In [53]:
#3d example
c=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [56]:
#need 4 0thblock ,1st row, 2ndcolum
c[0,1,1]

4

In [65]:
#replace
c[:,:,1] =[[9,9],[8,8]]#gives first column in both
print(c)

[[[1 9]
  [9 9]]

 [[5 8]
  [8 8]]]


In [67]:
c[:,1,:]=[[199,199],[188,188]]#gives first row in both
print(c)

[[[  1   9]
  [199 199]]

 [[  5   8]
  [188 188]]]


**Intialsing different types of arrays **


In [69]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [70]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [71]:
np.ones(4)

array([1., 1., 1., 1.])

In [72]:
np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [74]:
#np.full takes 2 parameters
#first one is size second one is value
np.full((2,2),(9,8),dtype='int16')

array([[9, 8],
       [9, 8]], dtype=int16)

In [76]:
#full_like reuse
np.full_like(a,4)

array([[4, 4, 4, 4, 4, 4, 4],
       [4, 4, 4, 4, 4, 4, 4]])

In [77]:
#random
np.random.rand(4,2)

array([[0.39914315, 0.00869548],
       [0.28741836, 0.90322775],
       [0.96823656, 0.76313981],
       [0.94902789, 0.50816842]])

In [83]:
#start fromzero to 7 or 9 or....any value gven in (paranthesis)
np.random.randint(9,size=(3,3))
np.random.randint(4,9,size=(3,3))

array([[7, 8, 6],
       [7, 6, 5],
       [5, 8, 5]])

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]] printing this


In [85]:
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [90]:
arr=np.array([[1,2,3]])
r1=np.repeat(arr,3,axis=0)
print(r1)


[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [91]:
arr=np.array([[1,2,3]])
r2=np.repeat(arr,3,axis=1)
print(r2)


[[1 1 1 2 2 2 3 3 3]]


In [93]:
a=np.ones((5,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [98]:
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [99]:
a[2,2]=9
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


copyingg

In [102]:
#copying arrays
a=np.array([1,2,3])
b=a
b[0]=100
print(b)#same reference
print(a)#same reference

[100   2   3]
[100   2   3]


In [104]:
a=np.array([1,2,3])
b=a.copy()
b[0]=100
print(b)
print(a)

[100   2   3]
[1 2 3]


maths

In [116]:
a=np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [117]:
print(a+2)
print(a-2)
print(a*2)
print(a/2)


[3 4 5 6]
[-1  0  1  2]
[2 4 6 8]
[0.5 1.  1.5 2. ]


In [120]:
a=np.array([1,2,3,4])
b=np.ones((1,4))
a+b

array([[2., 3., 4., 5.]])

In [121]:
a**2

array([ 1,  4,  9, 16])

In [122]:
np.sin(a)

array([ 0.84147098,  0.90929743,  0.14112001, -0.7568025 ])

In [123]:
np.tan(a)

array([ 1.55740772, -2.18503986, -0.14254654,  1.15782128])

linear algebra


In [127]:
a=np.full((2,3),1)#2x3 matrix of all 2s
print(a)
b=np.full((3,2),2)#2x3 matrix of all 2s
print(b)

[[1 1 1]
 [1 1 1]]
[[2 2]
 [2 2]
 [2 2]]


In [128]:
#matrix multiplication
np.matmul(a,b)

array([[6, 6],
       [6, 6]])

In [130]:
#find determinant
c=np.identity(3)
np.linalg.det(c)

1.0

statistics


In [138]:
stats=np.array([[1,2,3],[4,5,6]])
print(np.min(stats,axis=1))#gives min in rows
print(np.min(stats,axis=0))#gives min in columns



[1 4]
[1 2 3]


In [139]:
print(np.max(stats,axis=1))#gives max in rows
print(np.max(stats,axis=0))#gives max in columns

[3 6]
[4 5 6]


In [140]:
np.sum(stats)


21

reorganinsing arrays

In [144]:
before=np.array([[1,2,3,4],[5,6,7,8]])
print(before)


[[1 2 3 4]
 [5 6 7 8]]


In [145]:
after=before.reshape((2,2,2))
print(after)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [150]:
#verticlly stacking vectors
v1=np.array([1,2,3,4])
v2=np.array([5,6,7,8])
print(np.vstack([v1,v2]))
print(np.vstack([v1,v2,v1,v2]))

[[1 2 3 4]
 [5 6 7 8]]
[[1 2 3 4]
 [5 6 7 8]
 [1 2 3 4]
 [5 6 7 8]]


In [153]:
#horizontal stack
h1=np.ones((2,4))
h2=np.zeros((2,2))
np.hstack((h1,h2))

array([[1., 1., 1., 1., 0., 0.],
       [1., 1., 1., 1., 0., 0.]])

load data from file

In [160]:
f=np.genfromtxt('data.txt',delimiter=',')
print(f)
print(f.astype('int32'))

[[  1.  13.  21.  11. 196.  75.   4.   3.  34.   6.   7.   8.   0.   1.
    2.   3.   4.   5.]
 [  3.  42.  12.  33. 766.  75.   4.  55.   6.   4.   3.   4.   5.   6.
    7.   0.  11.  12.]
 [  1.  22.  33.  11. 999.  11.   2.   1.  78.   0.   1.   2.   9.   8.
    7.   1.  76.  88.]]
[[  1  13  21  11 196  75   4   3  34   6   7   8   0   1   2   3   4   5]
 [  3  42  12  33 766  75   4  55   6   4   3   4   5   6   7   0  11  12]
 [  1  22  33  11 999  11   2   1  78   0   1   2   9   8   7   1  76  88]]


Advanced indexing
boolean masking

In [161]:
f>10

array([[False,  True,  True,  True,  True,  True, False, False,  True,
        False, False, False, False, False, False, False, False, False],
       [False,  True,  True,  True,  True,  True, False,  True, False,
        False, False, False, False, False, False, False,  True,  True],
       [False,  True,  True,  True,  True,  True, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])

In [162]:
f<0

array([[False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False, False,
        False, False, False, False, False, False, False, False, False]])

In [163]:
f[f>50]#gives values which are greater than 50

array([196.,  75., 766.,  75.,  55., 999.,  78.,  76.,  88.])

In [164]:
np.any(f>50,axis=0)

array([False, False, False, False,  True,  True, False,  True,  True,
       False, False, False, False, False, False, False,  True,  True])

In [166]:
((f>50)&(f<100))

array([[False, False, False, False, False,  True, False, False, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False,  True, False,  True, False,
        False, False, False, False, False, False, False, False, False],
       [False, False, False, False, False, False, False, False,  True,
        False, False, False, False, False, False, False,  True,  True]])