In [2]:
import numpy as np


In [ ]:
a=np.array([1,2,3])
print(type(a),a.shape,a[0],a[1],a[2])
a[0]=5
print(a)

<class 'numpy.ndarray'> (3,) 1 2 3
[5 2 3]


In [ ]:
b=np.array([[1,2,3],[4,5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [ ]:
b[0]

array([1, 2, 3])

In [ ]:
print(b.shape)
print(b[0,0], b[0,1], b[1,0])

1 2 4


In [ ]:
a=np.zeros((2,2))
print(a)


[[0. 0.]
 [0. 0.]]


In [ ]:
np.ones((1,2))
print(a)

array([[1., 1.]])

In [ ]:
c=np.full((2,2), 7)
print(c)

[[7 7]
 [7 7]]


In [ ]:
d=np.eye(2)
print(d)

[[1. 0.]
 [0. 1.]]


In [ ]:
e=np.random.random((2,2))
print(e)

[[0.16639233 0.30364726]
 [0.89945317 0.5695936 ]]


Array Indexing


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
b=a[:2,1:3]
print(b)

[[2 3]
 [6 7]]


In [ ]:
print(a[0, 1])
b[0,0]

2


2

In [ ]:
print(a)
print(b)

[[2 3]
 [6 7]]


In [ ]:
a=np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


In [ ]:

row_r1 = a[1, :]
row_r2 = a[1:2, :]
row_r3 = a[[1], :]
print(row_r1, row_r1.shape)
print(row_r2, row_r2.shape)
print(row_r3, row_r3.shape)

[5 6 7 8] (4,)
[[5 6 7 8]] (1, 4)
[[5 6 7 8]] (1, 4)


In [ ]:
a = np.array([[1,2], [3, 4], [5, 6]])
print(a.shape)

(3, 2)


In [ ]:
print(a[[0, 1, 2], [0, 1, 0]])
print(np.array([a[0, 0], a[1, 1], a[2, 0]]))

[1 4 5]
[1 4 5]


In [ ]:
print(a[[0, 0], [1, 1]])
print(np.array([a[0, 1], a[0, 1]]))

[2 2]
[2 2]


In [ ]:
a = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
print(a)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [ ]:
b = np.array([0, 2, 0, 1])
print(b)
print(a[:, b])


[0 2 0 1]
[[ 1  3  1  2]
 [ 4  6  4  5]
 [ 7  9  7  8]
 [10 12 10 11]]


In [ ]:
a[np.arange(4)]
print(a)

[[21  2  3]
 [ 4  5 26]
 [27  8  9]
 [10 31 12]]


In [1]:
import numpy as np

a = np.array([[1,2], [3, 4], [5, 6]])
print(a)

bool_idx = (a > 2)

print(bool_idx)

[[1 2]
 [3 4]
 [5 6]]
[[False False]
 [ True  True]
 [ True  True]]


In [3]:
print(a[bool_idx])
print(a[a > 2])

[3 4 5 6]
[3 4 5 6]


DATA TYPES


In [14]:
x = np.array([1, 2])
y = np.array([1.0, 2.0],dtype=np.int64)
z = np.array([1, 2])
print(x.dtype, y.dtype, z.dtype)

int64 int64 int64


ARRAY MATH


In [5]:
x = np.array([[1,2],[3,4]], dtype=np.float64)
y = np.array([[5,6],[7,8]], dtype=np.float64)
# Elementwise sum; both produce the array
print(x + y)
print(np.add(x, y))


[[ 6.  8.]
 [10. 12.]]
[[ 6.  8.]
 [10. 12.]]


In [6]:
print(x - y)
print(np.subtract(x, y))


[[-4. -4.]
 [-4. -4.]]
[[-4. -4.]
 [-4. -4.]]


In [7]:
print(x * y)
print(np.multiply(x, y))



[[ 5. 12.]
 [21. 32.]]
[[ 5. 12.]
 [21. 32.]]


In [8]:
print(x / y)
print(np.divide(x, y))

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]


In [9]:

print(np.sqrt(x))

[[1.         1.41421356]
 [1.73205081 2.        ]]


In [15]:
x = np.array([[1,2],[3,4]])
y = np.array([[5,6],[7,8]])
v = np.array([9,10])
w = np.array([11, 12])
print(v.shape, w.shape)
# Inner product of vectors; both produce 219
print(v.dot(w))
print(np.dot(v, w))

print(x.dot(y))

(2,) (2,)
219
219
[[19 22]
 [43 50]]


In [11]:
z = np.eye(2)
print(x.dot(z))

[[1. 2.]
 [3. 4.]]


In [16]:
print(v @ w)

219


In [17]:
print(x.dot(v))
print(np.dot(x, v))
print(x @ v)



[29 67]
[29 67]
[29 67]


In [18]:
print(x.dot(y))
print(np.dot(x,y))
print(x@y)

[[19 22]
 [43 50]]


In [19]:
x = np.array([[1,2],[3,4]])

print(np.sum(x))


10


In [20]:
print(x)
print(np.sum(x, axis=0))
print(np.sum(x, axis=1))

[[1 2]
 [3 4]]
[4 6]
[3 7]


In [21]:
print(x)
print("transpose\n", x.T)

transpose
 [[1 3]
 [2 4]]


In [22]:
v = np.array([[1,2,3]])
print(v.shape)
print(v )
print("transpose\n", v.T)

transpose
 [ 9 10]


Broad Casting


In [23]:
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = np.empty_like(x)
for i in range(4):
    y[i, :] = x[i, :] + v

print(y)


[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [25]:
vv = np.tile(v, (4, 1))
print(vv)


[[1 0 1]
 [1 0 1]
 [1 0 1]
 [1 0 1]]


In [26]:
y = x + vv  # Add x and vv elementwise
print(y)

[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [27]:
import numpy as np

# We will add the vector v to each row of the matrix x,
# storing the result in the matrix y
x = np.array([[1,2,3], [4,5,6], [7,8,9], [10, 11, 12]])
v = np.array([1, 0, 1])
y = x + v  # Add v to each row of x using broadcasting
print(y)



[[ 2  2  4]
 [ 5  5  7]
 [ 8  8 10]
 [11 11 13]]


In [28]:
# Compute outer product of vectors
v = np.array([1,2,3])
w = np.array([4,5])
print(np.reshape(v, (3, 1)) * w)

[[ 4  5]
 [ 8 10]
 [12 15]]


In [29]:
x = np.array([[1,2,3], [4,5,6]])

print(x + v)

[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]
 [11 13 15]]


In [36]:
print(x * 2)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]
 [20 22 24]]
